name: Sign Artifact with COSE (Python)

on:
  workflow_dispatch:
    inputs:
      file_to_sign:
        description: 'Relative path to the file to sign'
        required: true
        type: string

jobs:
  sign:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies (latest pycose from GitHub)
        run: |
          pip install --upgrade pip
          pip install git+https://github.com/TimothyClaeys/pycose.git@master
          pip install cryptography

      - name: Write private key from secret (PEM format)
        run: |
          echo "${{ secrets.COSE_SIGN_KEY }}" > private_key.pem

      - name: Extract public key from private key
        run: |
          openssl ec -in private_key.pem -pubout -out public_key.pem

      - name: Sign file using cose_signer.py
        run: |
          python cose_signer.py "${{ github.event.inputs.file_to_sign }}" \
                 "${{ github.event.inputs.file_to_sign }}.cose"

      - name: Upload signed artifact and public key
        uses: actions/upload-artifact@v4
        with:
          name: signed-cose-file
          path: |
            ${{ github.event.inputs.file_to_sign }}.cose
            public_key.pem
