name: COSE Sign and Verify

on:
  push:
    paths:
      - '**.py'
      - 'sample_payload'
      - 'private_key.pem'
      - 'public_key.pem'

jobs:
  cose-sign-verify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install pycose cryptography

      - name: Display payload
        run: cat sample_payload

      - name: Sign payload
        run: python3 cose_signer.py sample_payload sample_payload.cose

      - name: Verify signature
        run: python3 cose_verifier.py sample_payload.cose public_key.pem
