name: Sign Artifact with COSE (Python)

on:
  workflow_dispatch:
    inputs:
      file_to_sign:
        description: 'Relative path to the file to sign'
        required: true
        type: string

jobs:
  sign:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install pycose from GitHub master + cryptography
        run: |
          pip install --no-cache-dir git+https://github.com/TimothyClaeys/pycose.git@master cryptography

      - name: Write private key from secret
        run: |
          echo "${{ secrets.COSE_SIGN_KEY }}" | base64 -d > private_key.pk8

      - name: Sign file
        run: |
          python cose_signer.py "${{ github.event.inputs.file_to_sign }}" \
                               "${{ github.event.inputs.file_to_sign }}.cose" \
                               private_key.pk8

      - name: Upload signed artifact
        uses: actions/upload-artifact@v4
        with:
          name: signed-cose-file
          path: ${{ github.event.inputs.file_to_sign }}.cose
